application: arfrank
version: 1
runtime: python
api_version: 1

default_expiration: "99d"

handlers:
- url: /images
  static_dir: images
- url: /js
  static_dir: js
- url: /css
  static_dir: css
- url: /xml
  static_dir: xml

- url: (.*)/.*
  script: main.py
